### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by Aerodlyn** [richbrant/dasmoto-project#5]
Overall, not a bad solution! You achieved the correct result in a reasonable amount of code.

The biggest issue I saw was relatively minor, and is more a matter of organization. The issue being that it is possible to combine some tags together to achieve the same effect in less lines of code. Another thing to keep in mind is that almost every HTML tag has the same CSS properties as another.

The only other issue is that in each of your spans, you reference the class 'Bluebold' which isn't defined in your CSS file. It is important to ensure the referenced values are defined.

Good job!

**Comment by richbrant** [comment]
Thanks
